title: Isaac Kosloski
theme: jekyll-theme-minimal

# Navegação para múltiplas páginas
# Links aparecerão no topo com base nesse menu
navigation:
  - title: 🇧🇷 Português
    url: /index.md
  - title: 🇺🇸 English
    url: /en.md

# Permite usar markdown com páginas personalizadas
markdown: kramdown
